define: &none null

dmpairs:
- A:
    drop: 0.0
    transforms: *none
  B:
    drop: 0.5
    transforms: *none

- A:
    drop: 0.5
    transforms: *none
  B:
    drop: 0.5
    transforms: *none

- A:
    drop: 0.25
    transforms: *none
  B:
    drop: 0.75
    transforms: *none
