define:
  - &none null
  - &rotate-180
    - name: RandomVerticalFlip
      kwargs:
        p: 1
    - name: ToTensor

dmpairs:
- A:
    drop: 0.0
    transforms: *none
  B:
    drop: 0.0
    transforms: *rotate-180

- A:
    drop: 0.0
    transforms: *none
  B:
    drop: 0.5
    transforms: *rotate-180

- A:
    drop: 0.5
    transforms: *none
  B:
    drop: 0.0
    transforms: *rotate-180

- A:
    drop: 0.5
    transforms: *none
  B:
    drop: 0.5
    transforms: *rotate-180

- A:
    drop: 0.75
    transforms: *none
  B:
    drop: 0.25
    transforms: *rotate-180

- A:
    drop: 0.25
    transforms: *none
  B:
    drop: 0.75
    transforms: *rotate-180
