define:
  - &none null
  - &little-blur
    - name: RandomVerticalFlip
      kwargs:
        p: 1
    - name: ToTensor

dmpairs:
- A:
    drop: 0.0
    transforms: *none
  B:
    drop: 0.0
    transforms: *little-blur

- A:
    drop: 0.0
    transforms: *none
  B:
    drop: 0.5
    transforms: *little-blur

- A:
    drop: 0.5
    transforms: *none
  B:
    drop: 0.0
    transforms: *little-blur

- A:
    drop: 0.5
    transforms: *none
  B:
    drop: 0.5
    transforms: *little-blur

- A:
    drop: 0.75
    transforms: *none
  B:
    drop: 0.25
    transforms: *little-blur

- A:
    drop: 0.25
    transforms: *none
  B:
    drop: 0.75
    transforms: *little-blur
