# Store configs for each metric to be used
mmd_rbf:
  class: mmd
  arguments:
    embedding_name: matrix
    kernel_name: rbf
mmd_laplace:
  class: mmd
  arguments:
    embedding_name: matrix
    kernel_name: laplace
# To do: Add in configs for OT metric
