# Store configs for each metric to be used
mmd_rbf:
  function: mmd
  arguments:
    embedding_name: matrix
    kernel_name: rbf
mmd_laplace:
  function: mmd
  arguments:
    embedding_name: matrix
    kernel_name: laplace
