trainer_kwargs:
  max_epochs: 10
  devices: "auto"
  accelerator: "auto"

model:
  lr: 0.05

wandb:
  entity: turing-arc
  project: ms2
  mode: online
  id_postfix: _test_run #this postfix MUST be changed on each run
